package com.airtel.prod.engg.joint.constant;

public class Query {

	public static final String MANHOLE_TABLE_INSERT_QUERY = "INSERT INTO MANHOLE_MASTER(ID,MANHOLE_NO,DUCT_COUNT,DIRECTION) VALUES(?,?,?,?)";
	
	public static final String DUCT_TABLE_INSERT_QUERY = "INSERT INTO DUCT_MASTER(ID,MANHOLEPK,DUCTID,CABLECOUNT,COLOR) VALUES(?,?,?,?,?)";
	
	public static final String CABLE_TABLE_INSERT_QUERY = "INSERT INTO CABLE_MASTER(ID,DUCTPK,CABLEID,CABLE_DIRECTION,TYPE,TUBE_ID,COLOR,CABLE_ORDER) VALUES(?,?,?,?,?,?,?,?)";
	
	public static final String CONNECTION_TABLE_INSERT_QUERY = "INSERT INTO CONNECTION_MASTER(END_ONE,END_TWO,JOINT_ID) VALUES (?,?,?)";
	
	public static final String JOINT_TABLE_INSERT_QUERY = "INSERT INTO JOINT_MASTER(JOINT_ID,CABLE_COUNT,MANHOLE_NUMBER,JOINT_ORDER) VALUES (?,?,?,?)";
	
	public static final String LOOP_TABLE_INSERT_QUERY = "INSERT INTO LOOP_MASTER(CABLEID,LOOP_DISTANCE,MANHOLE_NUMBER) VALUES (?,?,?)";
	
	
	public static final String JOINT_TABLE_SELECT_QUERY = "SELECT JOINT_ID as jointId,CABLE_COUNT as noOfCables,JOINT_ORDER as jointOrder FROM JOINT_MASTER WHERE MANHOLE_NUMBER = ?";
	
	public static final String CONNECTION_TABLE_SELECT_QUERY = "SELECT END_ONE as end1, END_TWO as end2 FROM CONNECTION_MASTER WHERE JOINT_ID = ?";
	
	public static final String CABLE_TABLE_SELECT_QUERY = "SELECT CABLEID as cableId, CABLE_DIRECTION as cableDirection, TYPE as cableType, TUBE_ID as tubeId, COLOR as color, DUCTPK as ductPk, CABLE_ORDER as cableOrder FROM CABLE_MASTER WHERE ID = ?";
	
	public static final String MANHOLE_TABLE_SELECT_QUERY = "SELECT DIRECTION as direction, DUCT_COUNT as noOfDucts, ID as id FROM MANHOLE_MASTER WHERE MANHOLE_NO = ?";
	
	public static final String DUCT_TABLE_SELECT_QUERY = "SELECT ID as id, DUCTID as ductId, CABLECOUNT as noOfCables, COLOR as color FROM DUCT_MASTER WHERE MANHOLEPK = ?";
	
	public static final String CABLE_TABLE_CABLE_LOOP_MAP_SELECT_QUERY = "SELECT distinct CABLEID from CABLE_MASTER WHERE DUCTPK = ?";
	
	public static final String LOOP_MASTER_SELECT_QUERY = "SELECT LOOP_DISTANCE FROM LOOP_MASTER WHERE CABLEID = ? AND MANHOLE_NUMBER = ?";
	
}
