package com.airtel.prod.engg.joint.constant;

public class Query {

	public static final String MANHOLE_TABLE_INSERT_QUERY = "INSERT INTO MANHOLE_MASTER(ID,MANHOLE_NO,OLMID,DUCT_COUNT,DIRECTION) VALUES(?,?,?,?,?)";
	
	public static final String DUCT_TABLE_INSERT_QUERY = "INSERT INTO DUCT_MASTER(ID,MANHOLEPK,DUCTID,CABLECOUNT,COLOR) VALUES(?,?,?,?,?)";
	
	public static final String CABLE_TABLE_INSERT_QUERY = "INSERT INTO CABLE_MASTER(ID,DUCTPK,CABLEID,CABLE_DIRECTION,TYPE,TUBE_ID,COLOR,CABLE_ORDER) VALUES(?,?,?,?,?,?,?,?)";
	
	public static final String CONNECTION_TABLE_INSERT_QUERY = "INSERT INTO CONNECTION_MASTER(END_ONE,END_TWO,JOINT_ID) VALUES (?,?,?)";
	
	public static final String JOINT_TABLE_INSERT_QUERY = "INSERT INTO JOINT_MASTER(JOINT_ID,CABLE_COUNT) VALUES (?,?)";
}
